import { defineConfig } from 'vite';
import react from '@vitejs/plugin-react';
import tailwindcss from '@tailwindcss/vite';
import path from 'node:path';
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';

const apiGeneratedDir = path.resolve(__dirname, '../../apps/api/src/generated');
const apiSpaShellPath = path.resolve(apiGeneratedDir, 'spa-shell.ts');

export default defineConfig({
  plugins: [
    react(),
    tailwindcss(),
    {
      name: 'spa-shell-embed',
      closeBundle() {
        const indexPath = path.resolve(__dirname, 'dist/index.html');
        if (!existsSync(indexPath)) {
          console.warn('spa-shell-embed: dist/index.html not found, skipping');
          return;
        }
        const html: string = readFileSync(indexPath, 'utf8');
        const output: string = `// Auto-generated by Vite build plugin - DO NOT EDIT.\nexport const SPA_HTML: string = ${JSON.stringify(html)};\n`;
        if (!existsSync(apiGeneratedDir)) {
          mkdirSync(apiGeneratedDir, { recursive: true });
        }
        writeFileSync(apiSpaShellPath, output);
      },
    },
  ],
  server: {
    proxy: {
      '/api': {
        target: 'http://localhost:8787',
        changeOrigin: true,
      },
    },
  },
  build: {
    outDir: 'dist',
    emptyOutDir: true,
    minify: 'terser',
    terserOptions: {
      compress: {
        drop_console: true,
        drop_debugger: true,
      },
    },
  },
});
