const PROVIDER_GOOGLE_GMAIL = 'google-gmail';
const PROVIDER_MICROSOFT_OUTLOOK = 'microsoft-outlook';

const CONNECTION_METHOD_OAUTH2 = 'oauth2';

const CONNECTED_APPLICATION_STATUS_DRAFT = 'draft';
const CONNECTED_APPLICATION_STATUS_CONNECTED = 'connected';
const CONNECTED_APPLICATION_STATUS_ERROR = 'error';

const PROVIDER_SUBSCRIPTION_STATUS_ACTIVE = 'active';
const PROVIDER_SUBSCRIPTION_STATUS_STOPPED = 'stopped';
const PROVIDER_SUBSCRIPTION_STATUS_ERROR = 'error';

const PROCESSED_MESSAGE_STATUS_PROCESSING = 'processing';

const SOURCE_TYPE_EMAIL = 'email';
const PROCESSED_MESSAGE_STATUS_SUMMARIZED = 'summarized';
const PROCESSED_MESSAGE_STATUS_SKIPPED = 'skipped';
const PROCESSED_MESSAGE_STATUS_ERROR = 'error';

const SUPPORTED_PROVIDER_CONNECTIONS = {
  [PROVIDER_GOOGLE_GMAIL]: CONNECTION_METHOD_OAUTH2,
  [PROVIDER_MICROSOFT_OUTLOOK]: CONNECTION_METHOD_OAUTH2,
} as const;

type ProviderId = keyof typeof SUPPORTED_PROVIDER_CONNECTIONS;
type ConnectionMethod = (typeof SUPPORTED_PROVIDER_CONNECTIONS)[ProviderId];
type ConnectedApplicationStatus =
  | typeof CONNECTED_APPLICATION_STATUS_DRAFT
  | typeof CONNECTED_APPLICATION_STATUS_CONNECTED
  | typeof CONNECTED_APPLICATION_STATUS_ERROR;
type ProviderSubscriptionStatus =
  | typeof PROVIDER_SUBSCRIPTION_STATUS_ACTIVE
  | typeof PROVIDER_SUBSCRIPTION_STATUS_STOPPED
  | typeof PROVIDER_SUBSCRIPTION_STATUS_ERROR;
type ProcessedMessageStatus =
  | typeof PROCESSED_MESSAGE_STATUS_PROCESSING
  | typeof PROCESSED_MESSAGE_STATUS_SUMMARIZED
  | typeof PROCESSED_MESSAGE_STATUS_SKIPPED
  | typeof PROCESSED_MESSAGE_STATUS_ERROR;

type SourceType = typeof SOURCE_TYPE_EMAIL;

export {
  CONNECTED_APPLICATION_STATUS_CONNECTED,
  CONNECTED_APPLICATION_STATUS_DRAFT,
  CONNECTED_APPLICATION_STATUS_ERROR,
  CONNECTION_METHOD_OAUTH2,
  PROCESSED_MESSAGE_STATUS_ERROR,
  PROCESSED_MESSAGE_STATUS_PROCESSING,
  PROCESSED_MESSAGE_STATUS_SKIPPED,
  PROCESSED_MESSAGE_STATUS_SUMMARIZED,
  PROVIDER_GOOGLE_GMAIL,
  PROVIDER_MICROSOFT_OUTLOOK,
  PROVIDER_SUBSCRIPTION_STATUS_ACTIVE,
  SOURCE_TYPE_EMAIL,
  PROVIDER_SUBSCRIPTION_STATUS_ERROR,
  PROVIDER_SUBSCRIPTION_STATUS_STOPPED,
  SUPPORTED_PROVIDER_CONNECTIONS,
};
export type { ConnectedApplicationStatus, ConnectionMethod, ProcessedMessageStatus, ProviderId, ProviderSubscriptionStatus, SourceType };
